# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [3]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../Weather_Database/WeatherPy_database.csv"

# Load the CSV file into a Pandas DataFrame
city_data_df = pd.read_csv(file_path)

# Display sample data
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
0,0,Thompson,CA,55.7435,-97.8558,57.362,44,75,2.57,broken clouds
1,1,Jamestown,US,42.0970,-79.2353,60.188,34,0,3.60,clear sky
2,2,Mataura,NZ,-46.1927,168.8643,34.106,99,100,4.04,snow
3,3,Yar-Sale,RU,66.8333,70.8333,37.886,87,90,6.46,overcast clouds
4,4,Odoyev,RU,53.9393,36.6864,43.376,88,100,4.21,overcast clouds

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [4]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [5]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
                                    
# Display sample data
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
5,5,Puerto Ayora,EC,-0.7393,-90.3518,80.564,87,61,3.13,broken clouds
14,14,Kutum,SD,14.2000,24.6667,83.066,20,100,5.53,overcast clouds
24,24,Katsuura,JP,35.1333,140.3000,77.342,87,100,10.09,overcast clouds
25,25,Abu Kamal,SY,34.4506,40.9171,86.126,14,0,5.58,clear sky
26,26,Hithadhoo,MV,-0.6000,73.0833,82.472,70,100,7.64,overcast clouds
32,32,Atuona,PF,-9.8000,-139.0333,76.892,69,63,10.33,broken clouds
36,36,Harlingen,US,26.1906,-97.6961,87.710,67,100,2.06,overcast clouds
38,38,Merauke,ID,-8.4667,140.3333,78.854,88,100,5.18,overcast clouds
39,39,Latung,PH,5.5000,120.8833,83.426,74,100,3.19,moderate rain
47,47,Touros,BR,-5.1989,-35.4608,81.140,62,30,7.45,scattered clouds

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [9]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_travel_cities = preferred_cities_df.dropna()

# Display sample data
clean_travel_cities.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
5,5,Puerto Ayora,EC,-0.7393,-90.3518,80.564,87,61,3.13,broken clouds
14,14,Kutum,SD,14.2000,24.6667,83.066,20,100,5.53,overcast clouds
24,24,Katsuura,JP,35.1333,140.3000,77.342,87,100,10.09,overcast clouds
25,25,Abu Kamal,SY,34.4506,40.9171,86.126,14,0,5.58,clear sky
26,26,Hithadhoo,MV,-0.6000,73.0833,82.472,70,100,7.64,overcast clouds

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [15]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df = clean_travel_cities[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# Display sample data
hotel_df.head(10)

            City Country  Max Temp       Description      Lat       Lng
5   Puerto Ayora      EC    80.564     broken clouds  -0.7393  -90.3518
14         Kutum      SD    83.066   overcast clouds  14.2000   24.6667
24      Katsuura      JP    77.342   overcast clouds  35.1333  140.3000
25     Abu Kamal      SY    86.126         clear sky  34.4506   40.9171
26     Hithadhoo      MV    82.472   overcast clouds  -0.6000   73.0833
32        Atuona      PF    76.892     broken clouds  -9.8000 -139.0333
36     Harlingen      US    87.710   overcast clouds  26.1906  -97.6961
38       Merauke      ID    78.854   overcast clouds  -8.4667  140.3333
39        Latung      PH    83.426     moderate rain   5.5000  120.8833
47        Touros      BR    81.140  scattered clouds  -5.1989  -35.4608

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

In [16]:
# Add a new empty column, "Hotel Name", to the hotel_df DataFrame
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
5,Puerto Ayora,EC,80.564,broken clouds,-0.7393,-90.3518,
14,Kutum,SD,83.066,overcast clouds,14.2000,24.6667,
24,Katsuura,JP,77.342,overcast clouds,35.1333,140.3000,
25,Abu Kamal,SY,86.126,clear sky,34.4506,40.9171,
26,Hithadhoo,MV,82.472,overcast clouds,-0.6000,73.0833,
32,Atuona,PF,76.892,broken clouds,-9.8000,-139.0333,
36,Harlingen,US,87.710,overcast clouds,26.1906,-97.6961,
38,Merauke,ID,78.854,overcast clouds,-8.4667,140.3333,
39,Latung,PH,83.426,moderate rain,5.5000,120.8833,
47,Touros,BR,81.140,scattered clouds,-5.1989,-35.4608,

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [17]:
# Review the parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [18]:
# Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude as parameters to the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make an API request and retrieve the JSON data from the hotel search
    hotels = requests.get(base_url, params=params).json()
    
    # Get the first hotel from the results and store the name, if a hotel isn't found skip the city
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

KeyboardInterrupt:

In [ ]:
# Display sample data
# YOUR CODE HERE

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [ ]:
# Drop the rows where there is no Hotel Name.
clean_hotel_df = # YOUR CODE HERE

# Display sample data
# YOUR CODE HERE

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [ ]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [ ]:
# Set the file name.
output_data_file = # YOUR CODE HERE

# Create a CSV file by using the clean_hotel_df DataFrame
# YOUR CODE HERE

### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [ ]:
# Review the formatting template provided
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [ ]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# Display sample data
hotel_info[:10]

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [ ]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [ ]:
# Add a marker layer for each city to the map. 
# YOUR CODE HERE

# Create a figure to add the Google map as a layer
# YOUR CODE HERE

# Display the figure containing the map
# YOUR CODE HERE